# Ch03. (1유형) 이상값 탐색

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Grace', 'Hannah', 'Ian', 'Judy'],
    'Salary': [3200, 3400, 3100, 8000, 3300,
               3600, 15500, 3000, 3400, 9500],
    'Age': [25, 28, 26, 27, 29,
            30, 26, 31, 32, 28]
}

df = pd.DataFrame(data)
df

      Name  Salary  Age
0    Alice    3200   25
1      Bob    3400   28
2  Charlie    3100   26
3    David    8000   27
4      Eve    3300   29
5    Frank    3600   30
6    Grace   15500   26
7   Hannah    3000   31
8      Ian    3400   32
9     Judy    9500   28

In [ ]:
# IQR 기준 탐색
# IQR = Q3(75%) - Q1(25%)
# 기준: Q1 - 1.5IQR 미만 or Q3 + 1.5IQR 초과

q1 = df['Salary'].quantile(0.25)
q3 = df['Salary'].quantile(0.75)
iqr = q3 - q1

outliers = df[(df['Salary'] < q1 - 1.5 * iqr) | (df['Salary'] > q3 + 1.5 * iqr)]
outliers

    Name  Salary  Age
6  Grace   15500   26

In [ ]:
import pandas as pd

data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
s = pd.Series(data)

# quantile(): 주어진 시리즈나 데이터프레임의 분위수(quantile)를 계산
# 0.25 Q1, 0.5 Q2(중앙값), 0.75 Q3

print(s.quantile(.25))
print(s.quantile(0.5))
print(s.quantile(.75))

32.5
55.0
77.5

In [ ]:
# 표준편차 기준 탐색
# 평균 +- 표준편차 기준
# 통상적으로 평균 +-2~3 표준편차 벗어난 값은 이상값으로 간주 

mean = df['Salary'].mean()
std = df['Salary'].std()

outliers = df[(df['Salary'] < mean - 2 * std) | (df['Salary'] > mean + 2 * std)]
outliers

    Name  Salary  Age
6  Grace   15500   26