# Ch09. (1유형) 문자열 처리

In [ ]:
import pandas as pd

data = {
    'Email': ['kim@gmail.com', 'lee@naver.com', 'park@daum.net', 'choi@gmail.com'],
    'Name': ['Kim', 'Lee', 'Park', 'Choi'],
    'Comment': ['Hello!!', 'Nice to meet you :)', '  Thanks!! ', 'ok~~~']
}

df = pd.DataFrame(data)
df

# 텍스트 컬럼의 정제, 분류, 검색 등 전처리 과정에서 문자열 처리 함수가 자주 사용

            Email  Name              Comment
0   kim@gmail.com   Kim              Hello!!
1   lee@naver.com   Lee  Nice to meet you :)
2   park@daum.net  Park            Thanks!!
3  choi@gmail.com  Choi                ok~~~

In [ ]:
# split(): 문자열 분리
# 앞에 str. 빼먹지 말기

df['Email'].str.split('@').str[1]

0    gmail.com
1    naver.com
2     daum.net
3    gmail.com
Name: Email, dtype: object

In [ ]:
# lower(): 소문자 변환
# upper(): 대문자 변환

df['Name'].str.lower()

0     kim
1     lee
2    park
3    choi
Name: Name, dtype: object

In [ ]:
# 2번 인덱스 접근

df['Comment'].loc[2]

'  Thanks!! '

In [5]:
# strip(): 양측 공백 제거
# lstrip()/rstrip(): 좌측/우측 공백 제거

df['Comment'].str.strip().loc[2]

'Thanks!!'

In [7]:
# contains(): 특정 문자열 포함 여부...Boolean 반환 -> df로 필터링

df[df['Email'].str.contains('gmail')]

            Email  Name  Comment
0   kim@gmail.com   Kim  Hello!!
3  choi@gmail.com  Choi    ok~~~

In [8]:
# replace(): 문자열 치환
# regex =True: 정규표현식으로 패턴 인식

df['Comment'].str.replace('!', '', regex=False)

0                  Hello
1    Nice to meet you :)
2                Thanks
3                  ok~~~
Name: Comment, dtype: object

In [ ]:
# 문자열 슬라이싱

df['Email'].str[:5]

0    kim@g
1    lee@n
2    park@
3    choi@
Name: Email, dtype: object