# Ch03. Pandas의 이해

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [90, 85, 78, np.nan]
s = pd.Series(data)
s

0    90.0
1    85.0
2    78.0
3     NaN
dtype: float64

In [10]:
data = {
    "이름" : ["철수", "영희", "민수"],
    "국어" : [90, 80, 85],
    "수학" : [85, 95, 88]
}
df = pd.DataFrame(data)
print(df['수학'].mean())
df

89.33333333333333

   이름  국어  수학
0  철수  90  85
1  영희  80  95
2  민수  85  88

In [4]:
df = pd.read_csv('countries.csv')
df

  Unnamed: 0  country      area     capital  population
0         KR    Korea     98480       Seoul    51780579
1         US      USA   9629091  Washington   331002825
2         JP    Japan    377835       Tokyo   125960000
3         CN    China   9596960     Beijing  1439323688
4         RU   Russia  17100000      Moscow   146748600
5         DE  Germany    357022      Berlin    83200000

In [5]:
# 1.기본사용
# pandas 라이브러리를 가져와 사용 가능
import pandas
df = pandas.read_csv('countries.csv')

# 2.별칭(Alias) 사용
# pandas 대신 pd 라는 짧은 이름으로 사용 가능
import pandas as pd
df = pd.read_csv('countries.csv')

# 3. 모듈 내 특정 함수만 가져오기
# math 모듈에서 sqrt 함수만 가져와 사용
from math import sqrt
sqrt(16)  # 4.0

# 4. 여러 함수 한 번에 가져오기
from math import sqrt, pi